branches:
  only:
    - master

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
shallow_clone: true
clone_folder: c:\projects\meshlab
# Build Configuration, i.e. Debug, Release, etc.
configuration:
  - release
#  - debug
  
environment:
  matrix:
    # Microsoft Visual Studio 64bit
#    - QTDIR: C:\Qt\5.10.0\msvc2015
#    - QTDIR: C:\Qt\5.10.0\msvc2015_64
    - QTDIR: C:\Qt\5.9.4\msvc2015_64
      VSVER: 14.0
#      SPEC: win32-msvc2015
      SPEC: win64-msvc2015     
      COMPILER: nmake
      PATH: C:\Program Files (x86)\NSIS\;%PATH%
      #ARTIFACT: $(APPVEYOR_PROJECT_NAME)-%APPVEYOR_REPO_TAG_NAME%.%APPVEYOR_BUILD_NUMBER%-win64.zip
      #ARTIFACT: $(APPVEYOR_PROJECT_NAME)-%APPVEYOR_REPO_TAG_NAME%-win64.zip



# Set paths, etc.
before_build:
#  - path
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd ..
  - git clone --depth=1 --branch=devel https://github.com/cnr-isti-vclab/vcglib.git
  - dir 
  - set DISTRIBNAME=MeshLab_%DATE:~-4%%DATE:~4,2%%DATE:~7,2%.zip
  # Set paths
  #- '%QTDIR%\bin\qtenv2.bat'
  - call "%QTDIR%\bin\qtenv2.bat"
  # Show qmake and make version
  - qmake -v
  # Detect architecture (32bit or 64bit)
  - if %QTDIR:_64=%==%QTDIR% (set ARCH=x86) else (set ARCH=x64)
  # Set more... if Microsoft Visual Studio
  - if %COMPILER%==nmake call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  # Show build folder
  - echo %APPVEYOR_BUILD_FOLDER%
  - echo %CONFIGURATION%
  - echo %ARCH%
  - echo %DISTRIBNAME%
 

artifacts:
 - path: src/%DISTRIBNAME%
 - name: %DISTRIBNAME%
 
# To run your custom scripts instead of automatic MSBuild
build_script:
  # Go to clone directory
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd src
  - cd external
  - qmake external.pro -r 
  - call %COMPILER%
  - dir lib
  - dir lib\win32-msvc
  - dir lib\win32-msvc2015
  # for some reason it seems that external get different defaults lib...
  - copy lib\win32-msvc\*.lib lib\win32-msvc2015
  - dir lib\win32-msvc2015
  - cd ..
  - dir
  # Run qmake for the REAL project
  # - qmake meshlab_mini.pro -r -spec %SPEC% "CONFIG+=%CONFIGURATION%"
  - qmake meshlab_full_appveyor.pro -r 
  - dir
  # Run compiler
  #- '%COMPILER%'
  - call %COMPILER%
  - dir
  - cd %APPVEYOR_BUILD_FOLDER% 
  - dir
  - cd src\distrib
  - dir
  - windeployqt --no-translations meshlab.exe
  - dir
  - cd %APPVEYOR_BUILD_FOLDER% 
  - cd src 
  - 7z a %DISTRIBNAME% distrib
  - dir
#  - cd ..\install
#  - makensis /V4 meshlab-64bit-appveyor.nsi
#  - dir ..\distrib
