blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/libigl/libigl/discussions/new?category_id=32617689
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/libigl/libigl/discussions/new?category_id=32617688
    about: Ask the community for help
