language: cpp
dist: xenial

script:
  - make -j2 VERBOSE=1 && make install
  - if [ "$CHEALPIX" == "Off" ]; then  make buildtests && make test; fi
  - if [ "$BUILD_DOC" == "On" ]; then  make doc; fi

#cache:
#  directories:
#    - ${TRAVIS_BUILD_DIR}/deps/cmake

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps


before_install:
  - export CHECKOUT_PATH=`pwd`;
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - export OpenGR_RELEASE_NAME="Super4PCS-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-${CXX}"
  - export OpenGR_RELEASE_DIR="${CHECKOUT_PATH}/${OpenGR_RELEASE_NAME}"
  - $CXX --version
  - cmake --version


matrix:
  include:
    # mac clang Release
    - env: BUILD_TYPE=Release BOOST=Off CHEALPIX=Off BUILD_DOC=Off
      os: osx
      compiler: clang


    # clang 5.0 Release
    - env: CLANG_VERSION=5.0 BUILD_TYPE=Release BOOST=Off CHEALPIX=Off BUILD_DOC=Off
      os: linux
      addons: &clang50
        apt:
          packages:
            - util-linux
            - clang-5.0
            - g++-7
            - cmake
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-5.0


    # gcc-7 Release
    - env: GCC_VERSION=7 BUILD_TYPE=Release BOOST=Off CHEALPIX=Off BUILD_DOC=Off
      os: linux
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - cmake
          sources:
            - ubuntu-toolchain-r-test


    ############################################################################
    # BOOST
    ############################################################################
    # mac clang Release
    - env: BUILD_TYPE=Release BOOST=On CHEALPIX=Off
      os: osx
      compiler: clang


    # clang 5.0 Release
    - env: CLANG_VERSION=5.0 BUILD_TYPE=Release BOOST=On CHEALPIX=Off BUILD_DOC=Off
      os: linux
      addons: &clang50
        apt:
          packages:
            - util-linux
            - clang-5.0
            - g++-7
            - cmake
            - libboost-filesystem-dev
            - libboost-system-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-5.0


    # gcc-7 Release
    - env: GCC_VERSION=7 BUILD_TYPE=Release BOOST=On CHEALPIX=Off BUILD_DOC=On
      os: linux
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - cmake
            - libboost-filesystem-dev
            - libboost-system-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test

    ############################################################################
    # Chealpix
    ############################################################################
    # mac clang
    - env: BUILD_TYPE=Release BOOST=On CHEALPIX=On
      os: osx
      compiler: clang


    # clang 5.0
    - env: CLANG_VERSION=5.0 BUILD_TYPE=Release BOOST=On CHEALPIX=On BUILD_DOC=Off
      os: linux
      addons: &clang50
        apt:
          packages:
            - util-linux
            - clang-5.0
            - g++-7
            - cmake
            - libboost-filesystem-dev
            - libboost-system-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-5.0


    # gcc-7
    - env: GCC_VERSION=7 BUILD_TYPE=Release BOOST=On CHEALPIX=On BUILD_DOC=Off
      os: linux
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - cmake
            - libboost-filesystem-dev
            - libboost-system-dev
          sources:
            - ubuntu-toolchain-r-test


install:
  - cd $CHECKOUT_PATH


  - mkdir -p build
  - cd build
  - if [ "$GCC_VERSION" == "5" ]; then CXX_FLAGS="${CXX_FLAGS} -DRANGES_CXX_CONSTEXPR=RANGES_CXX_CONSTEXPR11"; fi
  - if [ -n "$CLANG_VERSION" ]; then CXX_FLAGS="${CXX_FLAGS} -D__extern_always_inline=inline"; fi
  - cmake .. -DOpenGR_COMPILE_TESTS=TRUE -DIO_USE_BOOST=$BOOST -DENABLE_TIMING=FALSE -DOpenGR_USE_CHEALPIX=$CHEALPIX -DDL_DATASETS=FALSE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${OpenGR_RELEASE_DIR}/


# safelist
branches:
  except:
  - gh-pages


deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/doc/html
  github_token: $GITHUB_API_KEY
  on:
    branch: master
    condition: "$BUILD_DOC = On"


############################################################################
# Artifacts creation
############################################################################
#after_success:
#  - zip -r ${OpenGR_RELEASE_NAME}.zip ${OpenGR_RELEASE_DIR}

#deploy:
#  provider: releases
#  draft: true
#  skip_cleanup: true
#  api_key:
#    secure: inU1jKE5PfPyhONbz7OvNLggEAQ0RE4CwY+WaWLsteEXkd7jl+IsIsIJ52E8xSma15HZHw9cqTGlQcZ+Hk8fBJBC4b5wVFOvoVauyMGYY/askI9uQqsmhDzmGk7sbDv/RtPoMfEPOJ8Y78M+NqCBbF8j5Xn9K/xpVOCpQKwG8JJB0/3z/NUu6fmcBwFvu2rqcdqX6FpfZSDOYCZJ0pK7JGKgah4DmV7M71emIlj5GOj007rbhq/C4j4hb9/CyWnh65yC5SA9In/DBgX3t2ipjnOX19Ft/7upCjLDq4KlblmGexdSvN8S3HV6Bcr3lqNU2XcOHML7xeR87EVYclioEqz937rav4XEuhMaRlonY6nPPZUeSyFns29m2K194oupRzgf4FwsdmWdpZN51baO+zy2X+nAovrLGBEjr+rMrg6COsno4pKJT+CDG0UbE34DpnyNPx7rF8T++FzS8LUdIWTLZSHQSBlJhWX3EzAAy7KJ+xOiOXswg7T7D9LoErS8wygDw21ssW0z/vgFzvyOKbfT1O6B3SGnL+e5vnc1A9VqXm/Gp8Rs3lRCOilwC5HIWczJaczCJiHR+boImPNZXuhz9e3WIjMlJ/upqbpMnwKPC+pH4d6d6LWZzaDQDXSZ7bqShBvFQCgAkgy+IVPUU7AwKYkXlkNaba9J2xuRaA0=
#  file: ${OpenGR_RELEASE_NAME}.zip
#  tag_name: $TRAVIS_TAG  #https://github.com/travis-ci/travis-ci/issues/6132#issuecomment-303634652
#  on:
#    tags: true
