name: BuildMacOS

on:
  [push, pull_request]

jobs:
  macos_build:
    name: Build MeshLab (MacOS)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install dependencies
      run: |
        brew install libomp
        npm install -g appdmg
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: qtscript xmlpatterns
    - name: Setup env variables
      id: envs
      shell: bash
      run: |
        #sh install/macos/macos_setup_env.sh
        #necessary here on github actions:
        #echo '::set-env name=QTDIR::/usr/local/opt/qt'
        #echo '::add-path::/usr/local/opt/qt/bin'
        #echo '::set-env name=LD_LIBRARY_PATH::/usr/local/opt/qt/lib:${{env.LD_LIBRARY_PATH}}'
        #echo '::set-env name=PKG_CONFIG_PATH::/usr/local/opt/qt/lib:${{env.PKG_CONFIG_PATH}}'
        echo  ::set-output name=date::"$(cat ML_VERSION)"
    - name: Build MeshLab
      run: |
        sh install/macos/macos_build.sh
    - name: Deploy MeshLab
      run: |
        sh install/macos/macos_deploy.sh
    - name: Create DMG
      run: |
         sh install/macos/macos_dmg.sh
         mv distrib/MeshLab${{steps.envs.outputs.date}}.dmg distrib/MeshLab${{steps.envs.outputs.date}}-macos.dmg
    - name: Upload DMG
      uses: actions/upload-artifact@v1
      with:
        name: meshlab_macos_dmg
        path: distrib/MeshLab${{steps.envs.outputs.date}}-macos.dmg
