name: CompileMacOS

on:
  [push, pull_request]

jobs:
  macos_build:
    name: Build MeshLab (MacOS)
    runs-on: macos
    
    steps:
    - uses: actions/checkout@v2
    - name: Installing dependencies
      run: |
        brew install llvm libomp qt
        npm install -g appdmg
        cd ..
        git clone --depth=1 --branch=devel https://github.com/cnr-isti-vclab/vcglib.git
    - name: Setting env variables
      id: envs
      shell: bash
      run: |
        echo '::set-env name=QTDIR::/usr/local/opt/qt'
        echo '::add-path::/usr/local/opt/qt/bin'
        echo '::set-env name=LD_LIBRARY_PATH::/usr/local/opt/qt/lib:${{env.LD_LIBRARY_PATH}}'
        echo '::set-env name=PKG_CONFIG_PATH::/usr/local/opt/qt/lib:${{env.PKG_CONFIG_PATH}}'
        echo  ::set-output name=date::"$(date +%Y.%m)"   
    - name: Compiling MeshLab
      run: |
        cd src/
        qmake
        make -j4
    - name: Creating DMG
      run: |
         cd src/install/macx
         ./macinstall_latest.sh
         cd ../../..
         ls -la src/distrib/MeshLab${{steps.envs.outputs.date}}.dmg
         mv src/distrib/MeshLab${{steps.envs.outputs.date}}.dmg src/distrib/MeshLab${{steps.envs.outputs.date}}-macos.dmg
    - name: Uploading DMG
      uses: actions/upload-artifact@v1
      with:
        name: meshlab_macos
        path: src/distrib/MeshLab${{steps.envs.outputs.date}}-macos.dmg
