name: CompileWindows

on: [push, pull_request]

jobs:
  windows_build:
    name: Build MeshLab (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Installing QT
      uses: jurplel/install-qt-action@v2
      with:
        modules: qtscript xmlpatterns
    - name: Installing dependencies
      run: |
        cd ..
        git clone --depth=1 --branch=devel https://github.com/cnr-isti-vclab/vcglib.git
    - name: Compiling external
      run: |
        cd src\external
        qmake external.pro -r
        nmake
    - name: Compiling MeshLab
      run: |
        cd src\
        qmake meshlab_full.pro -r
        nmake
    - name: Creating MeshLab Portable ZIP
      run: |
        cd src\distrib
        windeployqt --no-translations meshlab.exe
    - name: Uploading Meshlab Portable 
      uses: actions/upload-artifact@v1
      with:
        name: meshlab_portable_windows
        path: src\distrib

  windows_build_cmake:
    name: Build MeshLab (Windows, CMake)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setting MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Installing QT
      uses: jurplel/install-qt-action@v2
      with:
        modules: qtscript xmlpatterns

    - name: Installing dependencies
      run: |
        cd ..
        git clone --depth=1 --branch=devel https://github.com/cnr-isti-vclab/vcglib.git

    - name: Configure
      run: |
        cd $env:GITHUB_WORKSPACE
        cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=install
        # -DBUILD_MINI=ON

    - name: Build
      run: |
        cmake --build $env:GITHUB_WORKSPACE/build --config RelWithDebInfo -j 4
        cmake --build $env:GITHUB_WORKSPACE/build --config RelWithDebInfo --target INSTALL
    - name: Uploading MeshLab Portable
      uses: actions/upload-artifact@v1
      with:
        name: meshlab_portable_cmake
        path: install
