name: MacOS

on:
  [push, pull_request]

jobs:
  macos_build:
    name: Build MeshLab (MacOS)
    runs-on: macos-latest
    strategy:
      matrix:
        precision: [single_precision, double_precision]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        brew install libomp
        npm install -g appdmg
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Setup env variables
      id: envs
      shell: bash
      run: |
        if [ "${{matrix.precision}}" == "double_precision" ]; then
          echo  ::set-output name=version::"$(cat ML_VERSION)d"
          echo  ::set-output name=artifact_suffix::"_double"
        else
          echo  ::set-output name=version::"$(cat ML_VERSION)"
          echo  ::set-output name=artifact_suffix::""
        fi
    - name: Configure and Build
      run: |
        sh scripts/${{ runner.os }}/1_build.sh --${{ matrix.precision }}
    - name: Deploy
      run: |
        sh scripts/${{ runner.os }}/2_deploy.sh
    - name: Create DMG
      run: |
        sh scripts/${{ runner.os }}/3_dmg.sh --${{ matrix.precision }}
        mv src/install/MeshLab${{steps.envs.outputs.version}}.dmg src/install/MeshLab${{steps.envs.outputs.version}}-macos.dmg
    - name: Upload APP
      uses: actions/upload-artifact@v1
      with:
        name: meshlab_macos_app${{steps.envs.outputs.artifact_suffix}}
        path: src/install/meshlab.app
    - name: Upload DMG
      uses: actions/upload-artifact@v1
      with:
        name: meshlab_macos_dmg${{steps.envs.outputs.artifact_suffix}}
        path: src/install/MeshLab${{steps.envs.outputs.version}}-macos.dmg
